# List of major NSE companies for the dropdown
TICKERS = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS", "SBIN.NS", "BHARTIARTL.NS", "ITC.NS",
    "LICI.NS", "HINDUNILVR.NS", "LT.NS", "BAJFINANCE.NS", "HCLTECH.NS", "MARUTI.NS", "SUNPHARMA.NS", "ADANIENT.NS",
    "KOTAKBANK.NS", "TITAN.NS", "ONGC.NS", "TATAMOTORS.NS", "NTPC.NS", "AXISBANK.NS", "ADANIGREEN.NS", "ADANIPORTS.NS",
    "ULTRACEMCO.NS", "WIPRO.NS", "POWERGRID.NS", "BAJAJFINSV.NS", "JSWSTEEL.NS", "TATASTEEL.NS", "M&M.NS", "LTIM.NS",
    "HAL.NS", "SIEMENS.NS", "DMART.NS", "DLF.NS", "VARROC.NS", "SBILIFE.NS", "PIDILITIND.NS", "GRASIM.NS",
    "BAJAJ-AUTO.NS", "BEL.NS", "TRENT.NS", "VBL.NS", "COALINDIA.NS", "HINDALCO.NS", "INDUSINDBK.NS", "BANKBARODA.NS",
    "EICHERMOT.NS", "GODREJCP.NS", "DIVISLAB.NS", "DRREDDY.NS", "CIPLA.NS", "TECHM.NS", "BPCL.NS", "HAVELLS.NS",
    "ABB.NS", "TATAPOWER.NS", "ADANIPOWER.NS", "AMBUJACEM.NS", "INDIGO.NS", "IOC.NS", "GAIL.NS", "BRITANNIA.NS",
    "CHOLAFIN.NS", "TORNTPHARM.NS", "MANKIND.NS", "ZOMATO.NS", "JIOFIN.NS", "PNB.NS", "LODHA.NS", "SHREECEM.NS",
    "ICICIGI.NS", "CANBK.NS", "TVSMOTOR.NS", "DABUR.NS", "NAUKRI.NS", "IRFC.NS", "ZYDUSLIFE.NS", "ATGL.NS",
    "VEDL.NS", "SRF.NS", "SBICARD.NS", "MUTHOOTFIN.NS", "BERGEPAINT.NS", "UNIONBANK.NS", "ICICIPRULI.NS",
    "MOTHERSON.NS", "BOSCHLTD.NS", "MARICO.NS", "JSWENERGY.NS", "PIIND.NS", "HDFCLIFE.NS", "ASHOKLEY.NS",
    "CUMMINSIND.NS", "ALKEM.NS", "PERSISTENT.NS", "IRCTC.NS", "TATAELXSI.NS", "APOLLOHOSP.NS", "ASTRAL.NS",
    "BALKRISIND.NS", "POLYCAB.NS", "MAXHEALTH.NS", "TORNTPOWER.NS", "MRF.NS", "UPL.NS", "LUPIN.NS",
    "OBEROIRLTY.NS", "INDHOTEL.NS", "PHOENIXLTD.NS", "PATANJALI.NS", "AUROPHARMA.NS", "YESBANK.NS", "IDFCFIRSTB.NS"
]

# Sort alphabetically
TICKERS.sort()
